const express = require("express")
const checkAuth = require("../middleware/checkAuth")
const { addPost, likePost, dislikePost, bookmarkPost, deletePost, updatePost, commentOnPost, getAllPost, getUserPost, getCommentsOfPost } = require("../controllers/post")
const router = express.Router()
router.post("/new", checkAuth, addPost)
router.post("/like/:id", checkAuth, likePost)
router.post("/dislike/:id", checkAuth, dislikePost)
router.post("/bookmark/:id", checkAuth, bookmarkPost)
router.delete("/:id", checkAuth, deletePost)
router.patch("/:id", checkAuth, updatePost)
router.post("/comment/:id", checkAuth, commentOnPost)
router.get("/all", checkAuth, getAllPost)
router.get("/comment/:id", checkAuth, getCommentsOfPost)
router.get("/my", checkAuth, getUserPost)
module.exports = router